homeassistant:
  # Name of the location where Home Assistant is running
  name: Mun So
  # Location required to calculate the time the sun rises and sets
  latitude: 20.9636894
  longitude: 105.8221005
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Ho_Chi_Minh
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_glob:
    light.*:
      custom_ui_state_card: state-card-custom-ui
    cover.*:
      custom_ui_state_card: state-card-custom-ui
    input_boolean.weather:
      custom_ui_state_card: custom-weather-card
      friendly_name: Weather
      config:
        weather: weather.yweather

# Show links to resources in log and frontend
#introduction:
customizer:
  custom_ui: local

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/custom-weather-card.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/custom-weather-card.html


weather:
  - platform: yweather
input_boolean:
  weather:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  ssl_certificate: /etc/letsencrypt/live/munso.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/munso.duckdns.org/privkey.pem
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: munso.duckdns.org
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

duckdns:
  domain: munso
  access_token: !secret duck_dns_token

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


python_script:


# Weather prediction
#sensor:
#  - platform: yr

sensor: !include_dir_merge_list sensors/

# Sensor connect to Raspi
binary_sensor: !include_dir_merge_list binary_sensors/

# Swtich relay connect to Raspi
switch: !include_dir_merge_list switchs/

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

mqtt:
  broker: 192.168.1.106

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: 7811dcb7bb6d
      key: 2ypq9y75v4pgj48f

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    home_interval: 10
    scan_options: " --privileged -sP "
    exclude:
     - 192.168.1.128 # Echo
     - 192.168.1.102 # Xiaomi gateway 78:11:dc:b7:bb:6d
     - 192.168.1.176 # FPT play b0:46:fc:c0:b2:d8 
     - 192.168.1.253 # RM pro 78:0f:77:00:bf:ac  
  - platform: mqtt
    devices:
      tatdat_iphone: 'hass/tatdat_iphone/localizacion'
      tatdat_note8: 'hass/tatdatnote8/localizacion'

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet