#- platform: google_travel_time
#  name: Tat Dat Work Travel
#  api_key: !secret GOOGLE_TRAVEL_API
#  origin: Home
#  destination: Work

#- platform: google_travel_time
#  name: Tat Dat Home Travel
#  api_key: !secret GOOGLE_TRAVEL_API
#  origin: Work
#  destination: Home

- platform: mqtt
  state_topic: 'owntracks/homeassistant/note8'
  name: 'Phone Battery (Tat Dat)'
  unit_of_measurement: '%'
  value_template: >
    {% if value_json.batt %}
      {{ value_json.batt }}
    {% else %}
      {{ states('sensor.phone_battery_tatdat') }}
    {% endif %}
- platform: mqtt
  state_topic: 'owntracks/homeassistant/note8'
  name: Connection (Tat Dat)'
  value_template: >
    {% if value_json.conn %}
      {% if value_json.conn == 'w' %}
        WiFi
      {% else %}
        4G
      {% endif %}
    {% else %}
      {{ states('sensor.connection_tatdat') }}
    {% endif %}
- platform: mqtt
  state_topic: 'owntracks/homeassistant/note8'
  name: 'GPS Accuracy'
  value_template: >
    {% if value_json.acc %}
      {{ value_json.acc }}
    {% else %}
      {{ states('sensor.gps_accuracy') }}
    {% endif %}

- platform: template
  sensors:
    battery_xiaomi_switch_01:
      friendly_name: 'Bedroom switch battery' 
      unit_of_measurement: '%'
      value_template: >
          {%- if states.binary_sensor.switch_158d0001e59b5c.attributes.battery_level %}
              {{ states.binary_sensor.switch_158d0001e59b5c.attributes.battery_level|round }}
          {% else %}
              {{ states.binary_sensor.switch_158d0001e59b5c.state }}
          {%- endif %}
      icon_template: '{%- if  states.binary_sensor.switch_158d0001e59b5c.attributes.battery_level <= 5 %}mdi:battery-outline{%- elif states.binary_sensor.switch_158d0001e59b5c.attributes.battery_level >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.binary_sensor.switch_158d0001e59b5c.attributes.battery_level|float / 10)|round*10}}{%- endif %}'
    battery_xiaomi_temperature:
      friendly_name: 'Bedroom temperature battery' 
      unit_of_measurement: '%'
      value_template: >
          {%- if states.binary_sensor.temperature_158d00020f527c.attributes.battery_level %}
              {{ states.binary_sensor.temperature_158d00020f527c.attributes.battery_level|round }}
          {% else %}
              {{ states.binary_sensor.temperature_158d00020f527c.state }}
          {%- endif %}
      icon_template: '{%- if  states.binary_sensor.temperature_158d00020f527c.attributes.battery_level <= 5 %}mdi:battery-outline{%- elif states.binary_sensor.temperature_158d00020f527c.attributes.battery_level >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.binary_sensor.temperature_158d00020f527c.attributes.battery_level|float / 10)|round*10}}{%- endif %}'
