- platform: template
  sensors:
    battery_xiaomi_switch_01:
      friendly_name: 'Bedroom switch battery' 
      unit_of_measurement: '%'
      value_template: >
          {%- if states.binary_sensor.switch_158d0001e59b5c.attributes.battery_level %}
              {{ states.binary_sensor.switch_158d0001e59b5c.attributes.battery_level|round }}
          {% else %}
              {{ states.binary_sensor.switch_158d0001e59b5c.state }}
          {%- endif %}
      icon_template: '{%- if  states.binary_sensor.switch_158d0001e59b5c.attributes.battery_level <= 5 %}mdi:battery-outline{%- elif states.binary_sensor.switch_158d0001e59b5c.attributes.battery_level >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.binary_sensor.switch_158d0001e59b5c.attributes.battery_level|float / 10)|round*10}}{%- endif %}'
    battery_xiaomi_temperature:
      friendly_name: 'Bedroom temperature battery' 
      unit_of_measurement: '%'
      value_template: >
          {%- if states.binary_sensor.temperature_158d00020f527c.attributes.battery_level %}
              {{ states.binary_sensor.temperature_158d00020f527c.attributes.battery_level|round }}
          {% else %}
              {{ states.binary_sensor.temperature_158d00020f527c.state }}
          {%- endif %}
      icon_template: '{%- if  states.binary_sensor.temperature_158d00020f527c.attributes.battery_level <= 5 %}mdi:battery-outline{%- elif states.binary_sensor.temperature_158d00020f527c.attributes.battery_level >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.binary_sensor.temperature_158d00020f527c.attributes.battery_level|float / 10)|round*10}}{%- endif %}'
