- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
  minute: 30

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_free
    - type: processor_use
    - type: ipv4_address
      arg: eth0
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: last_boot

- platform: command_line
    name: CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(2)  }}'