- platform: broadlink
  host: 192.168.1.253
  mac: '78:0f:77:00:bf:ac'
  timeout: 15
  switches:
    #TV Sony

    # FPT Play box
        
    # Air conditioner
    aircon_off:
      friendly_name: "Aircon off"
      command_on: 'JgDWAH0/DxAOMBAPDzAPEBAvDxAPMA8QDjAQEQ0wEC8PEA8wDxAPLxAvDzAOMBAPDxEOMBAvDxAPEQ4QDxEOMBEPDhEPEA8QDxINEg4wDhEPEQ4QDxEOMQ4QDxEOEQ8QDzAPEA8QDzEOEA8QDxEOMQ4wDxAPEA8RDhEPEQ4QDxEOEQ8QDxEOEg4RDjAOMQ4RDxENEg4RDhAPEQ4SDhEOEQ4wEA8QLw8QDxAPEQ8RDhAPEQ4SDhAPEA8RDjEOEA8RDjAQLw8vEC8PEA8QDxEPLxAQDhEPLxAADQUAAA=='    