- platform: broadlink
  host: 192.168.2.102
  mac: '34:ea:34:51:25:54'
  timeout: 15
  switches:
    #TV Sony

    # FPT Play box
        
    # Air conditioner
    aircon_off:
      friendly_name: "Aircon off"
      command_on: 'JgDWAH0/DxAOMBAPDzAPEBAvDxAPMA8QDjAQEQ0wEC8PEA8wDxAPLxAvDzAOMBAPDxEOMBAvDxAPEQ4QDxEOMBEPDhEPEA8QDxINEg4wDhEPEQ4QDxEOMQ4QDxEOEQ8QDzAPEA8QDzEOEA8QDxEOMQ4wDxAPEA8RDhEPEQ4QDxEOEQ8QDxEOEg4RDjAOMQ4RDxENEg4RDhAPEQ4SDhEOEQ4wEA8QLw8QDxAPEQ8RDhAPEQ4SDhAPEA8RDjEOEA8RDjAQLw8vEC8PEA8QDxEPLxAQDhEPLxAADQUAAA=='
    aircon_cool:
      friendly_name: "Aircon Cool"
      command_on: 'JgDWAH1ADREPMA4REC4PEQ4wDxEPMA8QDjENEg4wDzAOEQ4xDxAOMBAvDy8QLw8RDhAQMA4vEBAOEQ8RDhEOMBAQDxAOEg0xDy8QEA4RDxAPEA8RDhIOLxAQDxEOEA8wDxEOEQ4RDxAPMA4RDhEPMA8vDzAPEBAQDhEPEA4REA8PEQ4SDhAPMQ0SDhAPMA8QDxEOEQ8RDhAPEQ4RDxEPEA4wEA8QLw8RDxENEQ4RDxAPEQ8QDxEOEQ4RDjAQEA4SDTEPLw8vEDAOEBARDREPMA4wEBAOEQ4ADQUAAA=='
    aircon_dry:
      friendly_name: "Aircon Dry"
      command_on: 'JgDWAH4/Dw8PMA8QDzAPEA8wDxAPLxAQDjAQEA4wEC8PEA8vEBAOMBAvDzAOMBAPDxEOMBAvDxAPEQ4QDxEOMBAQDhEPEA8QDxIOEQ4RDhEPEA8QDxAPMBEODxEOEg4wDjAPEA8QDzEOMA8QDxEOEQ4wEA8PEQ4RDxASDg4RDhEPEA8RDhEPEQ8QDhIOLxAQDhIOEA8QDxEOEg4RDhAPEQ4wEBAOMBAQDhIOEA8QDxEOEQ8QDxEPEA4RDzAOEQ8QDzEOMA4wES0QEA4SDhEOMA8vEC8QEA8ADQUAAA=='
    aircon_heat:
      friendly_name: "Aircon Heat"
      command_on: 'JgDWAH0/DhEPLw8QDzAPEBAvDhEPMA4RDy8PEg4vEC8PEA8wDhEPLxAvEC8PLxAQDxENMBAvDxAPEg4QDxAPMA8RDREPEQ4wDy8QEA4RDxEPEA8QDxEPLw4REA8PEBAvDxAPEQ4RDy8PEQ8QDxEPEA4wEA8QEA8QDxAPEg0RDxAPEA8RDhEPMA8vEC8OMQ4QEBENEg4QDxEPEQ4RDhAPEQ8vDxAPMA8QDxEQDw8QEBAOEQ4SDxAPEA4RDy8QEA4SDi8QLxAvDy8QDw8RDhEQLw4wDxAQEA4ADQUAAA=='
    aircon_temp_18:
      friendly_name: "Aircon Temp 18"
      command_on: 'JgDWAH1ADw8PMA8QDzAPEA8wDhEPLw8RDjAQEA4wDzAOEQ8wDxAOMA8wDzAPLw8QEBEOLw8wDxAPEQ4RDxAPLw8RDhEPEA8wDxAPEQ8QDhEPEQ4RDxAPMA4RDhEPEA8wDy8QEQ0RDzAOEg0RDxAQLw8vDxEOEQ8QDxEOEQ8QDxEOEg0RDxEOEg0RDzAOMA8QDxEOEQ8QDxEOEQ8QDxAQEQ0wDxEOMA8QDxEPMA4QDxEOEQ8QDxEOEQ8QDzAPEQ4RDjEOLw8wDzAPEA8QDxAPMQ8PEDAOEQ4ADQUAAA=='