# Turn off door light when pir sensor off
- alias: 'Turn off door light when pir sensor off'
  trigger:
    platform: state
    entity_id: binary_sensor.main_door_pir
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  action:
    service: switch.turn_off
    entity_id: switch.front_light
